import React, { useState } from 'react';
import { OverlayTrigger, Popover, Button } from 'react-bootstrap'; // Importar componentes do react-bootstrap

const operations = {
  consultarDadosAnimal: {
    name: 'Consultar Dados do Animal',
    description: 'Busca os dados de um animal específico pelo seu número SISBOV.',
    params: [
      {
        name: 'numeroSisbov',
        description: 'O número de identificação SISBOV do animal (15 dígitos). Use 123456789012345 para sucesso ou qualquer outro valor para erro.',
        placeholder: 'Ex: 123456789012345',
        type: 'text',
      },
    ],
    exampleData: {
      numeroSisbov: '123456789012345', // Exemplo de sucesso
    },
    endpoint: '/.netlify/functions/consultar-animal',
  },
  incluirPropriedade: {
    name: 'Incluir Propriedade',
    description: 'Cadastra uma nova propriedade rural no sistema SISBOV. Use NIRF 123 para simular um erro.',
    params: [
      { name: '_nirf', description: 'Número do Imóvel na Receita Federal.', placeholder: 'Ex: 12345678901 (sucesso) ou 123 (erro)', type: 'text' },
      { name: '_incra', description: 'Código INCRA da propriedade.', placeholder: 'Ex: 123456789012', type: 'text' },
      { name: '_tipoPropriedade', description: 'Tipo da propriedade (código numérico).', placeholder: 'Ex: 1', type: 'number' },
      { name: '_nomePropriedade', description: 'Nome da fazenda.', placeholder: 'Ex: Fazenda Modelo', type: 'text' },
      { name: '_area', description: 'Área total da propriedade em hectares.', placeholder: 'Ex: 1000', type: 'number' },
      { name: '_logradouro', description: 'Endereço da propriedade.', placeholder: 'Ex: Rua Principal, 123', type: 'text' },
      { name: '_bairro', description: 'Bairro da propriedade.', placeholder: 'Ex: Centro', type: 'text' },
      { name: '_cep', description: 'CEP da propriedade.', placeholder: 'Ex: 70000000', type: 'text' },
      { name: '_codMunicipio', description: 'Código do município (IBGE).', placeholder: 'Ex: 5300108', type: 'text' },
    ],
    exampleData: {
      _nirf: '12345678901',
      _incra: '123456789012',
      _tipoPropriedade: '1',
      _nomePropriedade: 'Fazenda Exemplo',
      _area: '1000',
      _logradouro: 'Rua das Flores, 10',
      _bairro: 'Jardim',
      _cep: '70000000',
      _codMunicipio: '5300108',
    },
    endpoint: '/.netlify/functions/incluir-propriedade',
  },
  movimentarAnimal: {
    name: 'Movimentar Animal',
    description: 'Registra a movimentação de animais entre propriedades. Use idPropriedadeOrigem 99999 para simular um erro.',
    params: [
      { name: 'dataValidade', description: 'Data de validade da GTA (dd/MM/yyyy).', placeholder: 'Ex: 30/06/2025', type: 'date' },
      { name: 'dataEmissao', description: 'Data de emissão da GTA (dd/MM/yyyy).', placeholder: 'Ex: 29/06/2025', type: 'date' },
      { name: 'dataSaida', description: 'Data de saída dos animais da origem (dd/MM/yyyy).', placeholder: 'Ex: 29/06/2025', type: 'date' },
      { name: 'dataChegada', description: 'Data de chegada dos animais ao destino (dd/MM/yyyy).', placeholder: 'Ex: 29/06/2025', type: 'date' },
      { name: 'idPropriedadeOrigem', description: 'ID da propriedade de origem. Use 123 para sucesso, 99999 para erro.', placeholder: 'Ex: 123 (sucesso) ou 99999 (erro)', type: 'number' },
      { name: 'cpfProdutorOrigem', description: 'CPF do produtor de origem.', placeholder: 'Ex: 11122233344', type: 'text' },
      { name: 'cnpjProdutorOrigem', description: 'CNPJ do produtor de origem.', placeholder: 'Ex: 11222333000144', type: 'text' },
      { name: 'idPropriedadeDestino', description: 'ID da propriedade de destino.', placeholder: 'Ex: 456', type: 'number' },
      { name: 'cpfProdutorDestino', description: 'CPF do produtor de destino.', placeholder: 'Ex: 55566677788', type: 'text' },
      { name: 'cnpjProdutorDestino', description: 'CNPJ do produtor de destino.', placeholder: 'Ex: 55666777000188', type: 'text' },
      { name: 'numerosSISBOV', description: 'Lista de números SISBOV dos animais, separados por vírgula.', placeholder: 'Ex: BR.0001.00000000001,BR.0001.00000000002', type: 'text' },
    ],
    exampleData: {
      dataValidade: '30/06/2025',
      dataEmissao: '29/06/2025',
      dataSaida: '29/06/2025',
      dataChegada: '29/06/2025',
      idPropriedadeOrigem: '123',
      cpfProdutorOrigem: '11122233344',
      cnpjProdutorOrigem: '11222333000144',
      idPropriedadeDestino: '456',
      cpfProdutorDestino: '55566677788',
      cnpjProdutorDestino: '55666777000188',
      numerosSISBOV: 'BR.0001.00000000001,BR.0001.00000000002',
    },
    endpoint: '/.netlify/functions/movimentar-animal',
  },
  solicitarNumeracao: {
    name: 'Solicitar Numeração',
    description: 'Solicita um lote de números de identificação (brincos) ao SISBOV. Use qtdeSolicitada fora do range 1-100 para simular um erro.',
    params: [
      { name: 'cnpjFabrica', description: 'CNPJ da fábrica de brincos.', placeholder: 'Ex: 00111222000133', type: 'text' },
      { name: 'cpfProdutor', description: 'CPF do produtor que receberá os brincos.', placeholder: 'Ex: 11122233344', type: 'text' },
      { name: 'cnpjProdutor', description: 'CNPJ do produtor que receberá os brincos.', placeholder: 'Ex: 11222333000144', type: 'text' },
      { name: 'idPropriedade', description: 'ID da propriedade onde os brincos serão utilizados.', placeholder: 'Ex: 123', type: 'number' },
      { name: 'qtdeSolicitada', description: 'Quantidade de números desejada (entre 1 e 100 para sucesso).', placeholder: 'Ex: 10 (sucesso) ou 0 (erro)', type: 'number' },
      { name: 'tipoIdentificacao', description: 'Código do tipo de identificação (Ex: 1 para brinco).', placeholder: 'Ex: 1', type: 'number' },
    ],
    exampleData: {
      cnpjFabrica: '00111222000133',
      cpfProdutor: '11122233344',
      cnpjProdutor: '11222333000144',
      idPropriedade: '123',
      qtdeSolicitada: '10',
      tipoIdentificacao: '1',
    },
    endpoint: '/.netlify/functions/solicitar-numeracao',
  },
  incluirAnimal: {
    name: 'Incluir Animal',
    description: 'Registra um novo animal nascido no Brasil. Use dataNascimento 30/02/2023 para simular um erro.',
    params: [
      { name: 'dataIdentificacao', description: 'Data em que o animal foi identificado (dd/MM/yyyy).', placeholder: 'Ex: 01/01/2023', type: 'date' },
      { name: 'dataNascimento', description: 'Data de nascimento do animal (dd/MM/yyyy). Use 30/02/2023 para erro.', placeholder: 'Ex: 15/12/2022 (sucesso) ou 30/02/2023 (erro)', type: 'date' },
      { name: 'numeroProvisorio', description: 'Numeração provisória, se aplicável.', placeholder: 'Ex: PROV123', type: 'text' },
      { name: 'numeroDefinitivo', description: 'Numeração definitiva (brinco).', placeholder: 'Ex: DEF456', type: 'text' },
      { name: 'idPropriedadeNascimento', description: 'ID da propriedade onde o animal nasceu.', placeholder: 'Ex: 123', type: 'number' },
      { name: 'idPropriedadeLocalizacao', description: 'ID da propriedade onde o animal se encontra.', placeholder: 'Ex: 123', type: 'number' },
      { name: 'idPropriedadeResponsavel', description: 'ID da propriedade do responsável pelo animal.', placeholder: 'Ex: 123', type: 'number' },
      { name: 'numeroSisbov', description: 'O número de identificação oficial do SISBOV.', placeholder: 'Ex: BR.0001.00000000001', type: 'text' },
      { name: 'codigoRaca', description: 'Código da raça do animal.', placeholder: 'Ex: NELORE', type: 'text' },
      { name: 'tipoIdentificacao', description: 'Código do tipo de identificação (Ex: 1 para brinco).', placeholder: 'Ex: 1', type: 'number' },
      { name: 'sexo', description: 'Sexo do animal (M/F).', placeholder: 'Ex: M', type: 'select', options: ['M', 'F'] },
      { name: 'cnpjProdutor', description: 'CNPJ do produtor responsável.', placeholder: 'Ex: 11222333000144', type: 'text' },
      { name: 'cpfProdutor', description: 'CPF do produtor responsável.', placeholder: 'Ex: 11122233344', type: 'text' },
    ],
    exampleData: {
      dataIdentificacao: '01/01/2023',
      dataNascimento: '15/12/2022',
      numeroProvisorio: 'PROV123',
      numeroDefinitivo: 'DEF456',
      idPropriedadeNascimento: '123',
      idPropriedadeLocalizacao: '123',
      idPropriedadeResponsavel: '123',
      numeroSisbov: 'BR.0001.00000000001',
      codigoRaca: 'NELORE',
      tipoIdentificacao: '1',
      sexo: 'M',
      cnpjProdutor: '11222333000144',
      cpfProdutor: '11122233344',
    },
    endpoint: '/.netlify/functions/incluir-animal',
  },
  informarMorteAnimal: {
    name: 'Informar Morte de Animal',
    description: 'Registra o óbito de um animal no sistema SISBOV. Use numeroSisbovAnimal inexistente para simular erro.',
    params: [
      { name: 'numeroSisbovAnimal', description: 'Número SISBOV do animal que morreu.', placeholder: 'Ex: BR.0001.00000000001 (sucesso) ou BR.0001.99999999999 (erro)', type: 'text' },
      { name: 'dataMorte', description: 'Data do óbito (dd/MM/yyyy).', placeholder: 'Ex: 28/06/2025', type: 'date' },
      { name: 'codigoTipoMorte', description: 'Código do tipo de morte (Ex: 1 para Abate, 2 para Doença).', placeholder: 'Ex: 1', type: 'number' },
      { name: 'codigoCausaMorte', description: 'Código da causa específica da morte.', placeholder: 'Ex: 101', type: 'number' },
    ],
    exampleData: {
      numeroSisbovAnimal: 'BR.0001.00000000001',
      dataMorte: '28/06/2025',
      codigoTipoMorte: '1',
      codigoCausaMorte: '101',
    },
    endpoint: '/.netlify/functions/informar-morte-animal',
  },
  consultarPropriedade: {
    name: 'Consultar Propriedade',
    description: 'Busca os dados de uma propriedade específica pelo seu ID. Use ID 99999 para simular erro.',
    params: [
      { name: 'idPropriedade', description: 'ID da propriedade a ser consultada.', placeholder: 'Ex: 1001 (sucesso) ou 99999 (erro)', type: 'number' },
    ],
    exampleData: {
      idPropriedade: '1001',
    },
    endpoint: '/.netlify/functions/consultar-propriedade',
  },
  recuperarTabela: {
    name: 'Recuperar Tabela de Domínio',
    description: 'Recupera os registros de uma tabela de domínio do SISBOV (ex: raças, tipos de morte). Use idTabela 2 para raças, 999 para erro.',
    params: [
      { name: 'idTabela', description: 'ID da tabela a ser recuperada (Ex: 2 para Raças, 999 para erro).', placeholder: 'Ex: 2 (sucesso) ou 999 (erro)', type: 'number' },
    ],
    exampleData: {
      idTabela: '2',
    },
    endpoint: '/.netlify/functions/recuperar-tabela',
  },
  incluirProprietario: {
    name: 'Incluir Proprietário',
    description: 'Cadastra um novo proprietário (Pessoa Física ou Jurídica) no sistema SISBOV. Use CPF/CNPJ já existente para simular erro.',
    params: [
      { name: '_razaoSocial', description: 'Razão Social (para PJ).', placeholder: 'Ex: Empresa Teste Ltda.', type: 'text' },
      { name: '_cnpj', description: 'CNPJ (para PJ). Use 11222333000144 para sucesso, 99999999999999 para erro.', placeholder: 'Ex: 11222333000144', type: 'text' },
      { name: '_nome', description: 'Nome completo (para PF).', placeholder: 'Ex: João da Silva', type: 'text' },
      { name: '_telefone', description: 'Telefone de contato.', placeholder: 'Ex: 61988887777', type: 'text' },
      { name: '_email', description: 'Endereço de e-mail.', placeholder: 'Ex: joao.silva@example.com', type: 'text' },
      { name: '_cpf', description: 'CPF (para PF). Use 11122233344 para sucesso, 99999999999 para erro.', placeholder: 'Ex: 11122233344', type: 'text' },
      { name: '_sexo', description: 'Sexo (M/F).', placeholder: 'Ex: M', type: 'select', options: ['M', 'F'] },
      { name: '_logradouro', description: 'Logradouro do endereço.', placeholder: 'Ex: Rua Exemplo, 123', type: 'text' },
      { name: '_bairro', description: 'Bairro do endereço.', placeholder: 'Ex: Centro', type: 'text' },
      { name: '_cep', description: 'CEP do endereço.', placeholder: 'Ex: 70000000', type: 'text' },
      { name: '_codMunicipio', description: 'Código do município (IBGE).', placeholder: 'Ex: 5300108', type: 'text' },
    ],
    exampleData: {
      _razaoSocial: '',
      _cnpj: '',
      _nome: 'João da Silva',
      _telefone: '61988887777',
      _email: 'joao.silva@example.com',
      _cpf: '11122233344',
      _sexo: 'M',
      _logradouro: 'Rua Exemplo, 123',
      _bairro: 'Centro',
      _cep: '70000000',
      _codMunicipio: '5300108',
    },
    endpoint: '/.netlify/functions/incluir-proprietario',
  },
  recuperarTabela: {
    name: 'Recuperar Tabela de Domínio',
    description: 'Recupera os registros de uma tabela de domínio do SISBOV (ex: raças, tipos de morte). Use idTabela 2 para raças, 999 para erro.',
    params: [
      { name: 'idTabela', description: 'ID da tabela a ser recuperada (Ex: 2 para Raças, 999 para erro).', placeholder: 'Ex: 2 (sucesso) ou 999 (erro)', type: 'number' },
    ],
    exampleData: {
      idTabela: '2',
    },
    endpoint: '/.netlify/functions/recuperar-tabela',
  },
  resetDb: {
    name: 'Resetar Banco de Dados Simulado',
    description: 'Limpa todos os dados do banco de dados simulado (animais, propriedades, proprietários, etc.).',
    params: [],
    endpoint: '/.netlify/functions/reset-db',
  },
};
  recuperarTabela: {
    name: 'Recuperar Tabela de Domínio',
    description: 'Recupera os registros de uma tabela de domínio do SISBOV (ex: raças, tipos de morte). Use idTabela 2 para raças, 999 para erro.',
    params: [
      { name: 'idTabela', description: 'ID da tabela a ser recuperada (Ex: 2 para Raças, 999 para erro).', placeholder: 'Ex: 2 (sucesso) ou 999 (erro)', type: 'number' },
    ],
    exampleData: {
      idTabela: '2',
    },
    endpoint: '/.netlify/functions/recuperar-tabela',
  },
  resetDb: {
    name: 'Resetar Banco de Dados Simulado',
    description: 'Limpa todos os dados do banco de dados simulado (animais, propriedades, proprietários, etc.).',
    params: [],
    endpoint: '/.netlify/functions/reset-db',
  },
};

export default App;
